# Change these first
owner: githinho # Your GitHub organization or username, where this repository lives
repo: jadrolinija-upptime # The name of this repository

sites:
  - name: Jadrolinija
    url: https://www.jadrolinija.hr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /jadrolinija-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jadrolinija-Upptime
  introTitle: "Track uptime of Jadrolinija website"
  introMessage: "Status page for Jadrolinija website, which is used for checking the schedule and buying online tickets for ferries in Croatia. This website usually doesn't work when you need it the most. This is an attempt to get the data about uptime and see in which periods the website is usually down."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
